language: java

# We can specify a list of JDKs to be used for testing

jdk:
 - openjdk11


deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - src/main/java/io/github/kreattang/Travis_CI_Tutorial/trityp.java
  on:
    tags: true
    branch: tag
    repo: kreattang/Travis_CI_Tutorial
